[package]
edition      = "2024"
name         = "esp32c6-led"
rust-version = "1.88"
version      = "0.1.0"

[[bin]]
name = "esp32c6-led"
path = "./src/bin/main.rs"

[dependencies]
esp-hal = { version = "~1.1.0", features = ["esp32c6", "unstable"] }
esp-bootloader-esp-idf = { version = "0.5.0", features = ["esp32c6"] }
esp-println = { version = "0.17.0", features = ["esp32c6", "log-04"] }
libm = "0.2"

# Scheduling support and the Embassy integration for the ESP32-C6.
esp-rtos = { version = "=0.3.0", features = ["esp32c6", "embassy", "log-04"] }
embassy-executor = "=0.10.0"# Runs async tasks; provides the Spawner type used by async main.
embassy-time = "=0.5.0" # Async timers, backed by the timer integration above.

# Versions pinned to ensure compatibility with zigbee-rs:

# Pinning esp32c6 PAC to known working version
esp32c6-pac = { package = "esp32c6", version = "=0.23.2" }

# Driver for the ESP32-C6's IEEE 802.15.4 radio
esp-radio = { version = "=1.0.0-beta.0", features = [
    "esp32c6",
    "ieee802154",
    "unstable",
] }

# Adapts the radio driver to the interface expected by zigbee-rs.
zigbee-mac = { version = "=0.1.0", features = ["esp32c6"] }

# Needed for heap-allocated radio/MAC buffers
esp-alloc = { version = "=0.10.0", features = ["esp32c6"] }

# Zigbee stack, including support for storage (which we need for authentication/security purposes like storing keys and counters)
zigbee = { version = "=0.1.0", features = ["storage"] }

# Provides access to the ESP32-C6 flash memory
esp-storage = { version = "=0.9.0", features = ["esp32c6"] }

# Contains some utilities for working with flash memory
embassy-embedded-hal = "=0.5.0"

# Provides storage allocated at compile time but which can be initialized at runtime
static_cell = "2.1"

# For fine-tuning these settings, please refer to https://doc.rust-lang.org/cargo/reference/profiles.html
[profile.dev]
# The default debug profile is too slow and too big for resource-constrained devices.
# Always build with some optimizations enabled.
opt-level = "s"

[profile.release]
codegen-units = 1     # LLVM can perform better optimizations using a single thread
debug         = 2     # prefer slower builds but better debugging experience
lto           = 'fat'
opt-level     = 's'


[patch.crates-io]
# Load zigbee and related workspace deps from my fork, also explicitly list zigbee-mac, which is a direct dependency
# in this project, and should probably also come from my fork.
zigbee = { git = "https://github.com/hnsr/zigbee-rs.git", rev = "99d3387299dd4b5ac6685d6c1cb38d846a1d6b3b" }
zigbee-mac = { git = "https://github.com/hnsr/zigbee-rs.git", rev = "99d3387299dd4b5ac6685d6c1cb38d846a1d6b3b" }